#!/usr/bin/env python3
"""Dump the authoritative list of Minecraft debug shortcuts.

The F3 + Q in-game help list is built from `debug.*.help` translation keys, and
every debug action is a rebindable key mapping named `key.debug.*`. Both live in
`assets/minecraft/lang/en_us.json` inside the vanilla client jar, so the list can
be extracted for any version without launching the game.

Usage:
    python tools/dump_debug_shortcuts.py                 # latest release
    python tools/dump_debug_shortcuts.py 1.21.11         # specific version
    python tools/dump_debug_shortcuts.py --format md     # markdown tables
"""

import argparse
import io
import json
import pathlib
import sys
import urllib.request
import zipfile

MANIFEST = "https://launchermeta.mojang.com/mc/game/version_manifest_v2.json"
CACHE = pathlib.Path(__file__).resolve().parent / ".cache"


def fetch(url: str) -> bytes:
    with urllib.request.urlopen(url, timeout=300) as response:
        return response.read()


def client_jar(version: str | None) -> tuple[str, bytes]:
    manifest = json.loads(fetch(MANIFEST))
    version = version or manifest["latest"]["release"]
    try:
        entry = next(v for v in manifest["versions"] if v["id"] == version)
    except StopIteration:
        sys.exit(f"unknown version: {version}")

    CACHE.mkdir(exist_ok=True)
    cached = CACHE / f"client-{version}.jar"
    if not cached.exists():
        meta = json.loads(fetch(entry["url"]))
        cached.write_bytes(fetch(meta["downloads"]["client"]["url"]))
    return version, cached.read_bytes()


def lang_entries(jar: bytes) -> dict[str, str]:
    archive = zipfile.ZipFile(io.BytesIO(jar))
    return json.loads(archive.read("assets/minecraft/lang/en_us.json"))


def collect(lang: dict[str, str]) -> tuple[dict[str, str], dict[str, str]]:
    help_lines = {k: v for k, v in lang.items() if k.startswith("debug.") and k.endswith(".help")}
    bindings = {k: v for k, v in lang.items() if k.startswith("key.debug.")}
    return help_lines, bindings


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", nargs="?", help="Minecraft version (default: latest release)")
    parser.add_argument("--format", choices=("text", "md", "json"), default="text")
    args = parser.parse_args()

    version, jar = client_jar(args.version)
    help_lines, bindings = collect(lang_entries(jar))

    if args.format == "json":
        json.dump({"version": version, "help": help_lines, "bindings": bindings},
                  sys.stdout, indent=2, ensure_ascii=False)
        print()
        return

    if args.format == "md":
        print(f"<!-- generated by tools/dump_debug_shortcuts.py for Minecraft {version} -->\n")
        print("| Shortcut | Action |\n|---|---|")
        for value in help_lines.values():
            shortcut, _, action = value.partition(" = ")
            print(f"| `{shortcut}` | {action or value} |")
        print(f"\n| Key binding | Name |\n|---|---|")
        for key, value in sorted(bindings.items()):
            print(f"| `{key}` | {value} |")
        return

    print(f"Minecraft {version}")
    print(f"\nF3 + Q help list ({len(help_lines)} entries):")
    for value in help_lines.values():
        print(f"  {value}")
    print(f"\nRebindable debug key mappings ({len(bindings)}):")
    for key, value in sorted(bindings.items()):
        print(f"  {key:<38} {value}")


if __name__ == "__main__":
    main()
