#!/usr/bin/env python3
"""Generate the mod's language files.

Names and descriptions live here rather than in the JSON so both languages stay in step: every
entry carries its English and Russian text on one line. The descriptions are drawn from what each
debug entry actually prints or draws in 26.2.

Usage:
    python tools/make_lang.py
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1] / "src/main/resources/assets/debugmenu/lang"

UI = {
    "menu.debugmenu.open":             ("Debug Menu", "Меню отладки"),
    "menu.debugmenu.title":            ("Debug Menu", "Меню отладки"),
    "menu.debugmenu.combo":            ("%s + %s", "%s + %s"),
    "menu.debugmenu.on":               ("On", "Вкл"),
    "menu.debugmenu.off":              ("Off", "Выкл"),
    "menu.debugmenu.restore_defaults": ("Reset", "Сброс"),
    "menu.debugmenu.run":              ("Run", "Выполнить"),
    "menu.debugmenu.section.parameters": ("Parameters", "Параметры"),
    "menu.debugmenu.section.actions":    ("Actions", "Действия"),
    "key.debugmenu.open":               ("Open Debug Menu", "Открыть меню отладки"),
}

# key, en name, en description, ru name, ru description
E = [
    ("overlay", "Debug Overlay",
     "Master switch for the F3 screen: entries set to overlay-only show while it is open.",
     "Отладочный экран",
     "Главный переключатель F3: записи в режиме «только в оверлее» видны, пока он открыт."),
    ("advanced_tooltips", "Advanced Tooltips",
     "Adds the item id, durability and component data to item tooltips.",
     "Расширенные подсказки",
     "Добавляет в подсказки предметов идентификатор, прочность и данные компонентов."),
    ("focus_pause", "Pause on Lost Focus",
     "Pauses singleplayer when the game window loses focus.",
     "Пауза при потере фокуса",
     "Ставит одиночную игру на паузу, когда окно теряет фокус."),

    ("profiler_chart", "Profiler Chart",
     "Pie chart on the overlay showing where the frame time goes.",
     "График профилировщика",
     "Круговая диаграмма поверх экрана: на что уходит время кадра."),
    ("fps_charts", "FPS Charts",
     "Frame time graph over the last seconds.",
     "Графики кадров",
     "График времени кадра за последние секунды."),
    ("network_charts", "Network Charts",
     "Ping and bandwidth graphs for the current connection.",
     "Сетевые графики",
     "Графики пинга и трафика текущего соединения."),
    ("lightmap_texture", "Lightmap Texture",
     "Draws the lightmap texture the renderer samples for lighting.",
     "Текстура карты освещения",
     "Показывает текстуру карты освещения, из которой отрисовщик берёт значения."),

    ("reload_chunks", "Reload Chunks",
     "Rebuilds the geometry of every loaded chunk.",
     "Перезагрузить чанки",
     "Пересобирает геометрию всех загруженных чанков."),
    ("reload_resource_packs", "Reload Resource Packs",
     "Reloads textures, models, sounds and shaders from the resource packs.",
     "Перезагрузить ресурспаки",
     "Перезагружает текстуры, модели, звуки и шейдеры из ресурспаков."),
    ("clear_chat", "Clear Chat",
     "Clears the chat history.",
     "Очистить чат",
     "Очищает историю чата."),
    ("copy_location", "Copy Location",
     "Copies your position to the clipboard as an /execute ... run tp command.",
     "Скопировать координаты",
     "Копирует вашу позицию в буфер обмена как команду /execute ... run tp."),
    ("dump_version", "Dump Version Info",
     "Prints the client, data and pack versions to chat.",
     "Вывести версии",
     "Выводит в чат версии клиента, данных и паков."),
    ("dump_dynamic_textures", "Dump Dynamic Textures",
     "Saves every texture atlas as a PNG inside the game directory.",
     "Выгрузить текстуры",
     "Сохраняет все текстурные атласы в PNG внутри каталога игры."),
    ("profiling", "Start/Stop Profiling",
     "Records a profiling run and saves the result under debug/.",
     "Профилирование",
     "Записывает сеанс профилирования и сохраняет результат в каталог debug/."),
    ("debug_options", "Debug Options",
     "Opens the vanilla Debug Options screen.",
     "Настройки отладки",
     "Открывает ванильный экран Debug Options."),
    ("cycle_spectator", "Cycle Spectator",
     "Switches between spectator and your previous game mode; needs operator permission.",
     "Режим наблюдателя",
     "Переключает между наблюдателем и предыдущим режимом игры; требуются права оператора."),

    ("game_version", "Game Version",
     "Client version, launched version and the client name reported by the mod loader.",
     "Версия игры",
     "Версия клиента, версия запуска и имя клиента, сообщаемое загрузчиком модов."),
    ("fps", "FPS",
     "Frames per second, the frame limit and whether vsync is on.",
     "Кадры в секунду",
     "Частота кадров, ограничение частоты и состояние вертикальной синхронизации."),
    ("tps", "TPS",
     "Server tick rate, plus the average packets sent and received.",
     "Тики в секунду",
     "Частота тиков сервера, а также среднее число отправленных и принятых пакетов."),
    ("memory", "Memory",
     "Heap use as a percentage and in MiB, with the allocation rate.",
     "Память",
     "Занятость кучи в процентах и МиБ, а также скорость выделения памяти."),
    ("detailed_memory", "Detailed Memory",
     "Heap and non-heap usage read from the JVM memory bean.",
     "Подробная память",
     "Использование heap и non-heap, считанное через JVM MemoryMXBean."),
    ("system_specs", "System Specs",
     "Processor, graphics device info and the Java version the client runs on.",
     "Характеристики системы",
     "Процессор, данные видеоустройства и версия Java, на которой работает клиент."),
    ("looking_at_block_state", "Block Under Crosshair",
     "Identifier and block state properties of the block you are looking at.",
     "Блок под прицелом",
     "Идентификатор и свойства состояния блока, на который вы смотрите."),
    ("looking_at_block_tags", "Block Tags",
     "Tags of the block under the crosshair.",
     "Теги блока",
     "Теги блока под прицелом."),
    ("looking_at_fluid_state", "Fluid Under Crosshair",
     "Identifier and fluid state of the fluid you are looking at.",
     "Жидкость под прицелом",
     "Идентификатор и состояние жидкости, на которую вы смотрите."),
    ("looking_at_fluid_tags", "Fluid Tags",
     "Tags of the fluid under the crosshair.",
     "Теги жидкости",
     "Теги жидкости под прицелом."),
    ("looking_at_entity", "Entity Under Crosshair",
     "Registered name of the entity the crosshair is on.",
     "Существо под прицелом",
     "Зарегистрированное имя существа, на которое наведён прицел."),
    ("looking_at_entity_tags", "Entity Tags",
     "Tags of the entity under the crosshair.",
     "Теги существа",
     "Теги существа под прицелом."),
    ("chunk_render_stats", "Chunk Render Stats",
     "Counts of rendered and queued chunk sections.",
     "Статистика отрисовки чанков",
     "Число отрисованных секций чанков и секций в очереди."),
    ("chunk_generation_stats", "Chunk Generation Stats",
     "Generation stage of the chunk you stand in; integrated server only.",
     "Статистика генерации чанка",
     "Стадия генерации чанка, в котором вы стоите; только на встроенном сервере."),
    ("entity_render_stats", "Entity Render Stats",
     "How many entities are drawn out of those loaded.",
     "Статистика отрисовки существ",
     "Сколько существ отрисовано из числа загруженных."),
    ("particle_render_stats", "Particle Count",
     "Number of particles currently alive.",
     "Число частиц",
     "Количество частиц, существующих в данный момент."),
    ("chunk_source_stats", "Chunk Source Stats",
     "Client chunk cache statistics: loaded and cached chunks.",
     "Статистика источника чанков",
     "Статистика клиентского кэша чанков: загруженные и закэшированные чанки."),
    ("player_position", "Player Position",
     "Block coordinates, chunk coordinates and the direction you face.",
     "Позиция игрока",
     "Координаты блока, координаты чанка и направление взгляда."),
    ("player_section_position", "Section-Relative Position",
     "Your coordinates inside the current 16x16x16 chunk section.",
     "Позиция внутри секции",
     "Ваши координаты внутри текущей секции чанка 16×16×16."),
    ("light_levels", "Light Levels",
     "Block light and sky light at your position, read from the light engine.",
     "Уровни освещения",
     "Освещение от блоков и от неба в вашей позиции, считанное из движка света."),
    ("heightmap", "Heightmaps",
     "Heightmap value at your position for each heightmap type.",
     "Карты высот",
     "Значение карты высот в вашей позиции для каждого типа карты."),
    ("biome", "Biome",
     "Biome at your position.",
     "Биом",
     "Биом в вашей позиции."),
    ("local_difficulty", "Local Difficulty",
     "Local difficulty, moon brightness and how long the chunk has been inhabited.",
     "Локальная сложность",
     "Локальная сложность, яркость луны и время обжитости чанка."),
    ("day_count", "Day Count",
     "Number of in-game days elapsed in the overworld.",
     "Счётчик дней",
     "Число прошедших игровых дней в обычном мире."),
    ("entity_spawn_counts", "Mob Spawn Counts",
     "Mobs per spawn category and the number of spawnable chunks; integrated server only.",
     "Счётчики спавна мобов",
     "Мобы по категориям спавна и число чанков, пригодных для спавна; только на встроенном сервере."),
    ("sound_mood", "Sound Channels",
     "Playing and streaming sound channels, plus the cave mood level.",
     "Звуковые каналы",
     "Проигрываемые и потоковые звуковые каналы, а также уровень пещерного эффекта."),
    ("sound_cache", "Sound Cache",
     "Number of cached sound buffers and the memory they take.",
     "Кэш звуков",
     "Число закэшированных звуковых буферов и занимаемая ими память."),
    ("post_effect", "Post Effect",
     "Identifier of the post-processing shader currently applied.",
     "Пост-эффект",
     "Идентификатор применённого сейчас шейдера постобработки."),
    ("entity_hitboxes", "Entity Hitboxes",
     "Draws entity hitboxes and a line showing where each entity looks.",
     "Хитбоксы существ",
     "Рисует хитбоксы существ и линию направления их взгляда."),
    ("chunk_borders", "Chunk Borders",
     "Draws the borders of the chunk you stand in and its section grid.",
     "Границы чанков",
     "Рисует границы чанка, в котором вы стоите, и сетку его секций."),
    ("3d_crosshair", "3D Crosshair",
     "Replaces the crosshair with three axis lines showing world orientation.",
     "Трёхмерный прицел",
     "Заменяет прицел тремя осевыми линиями, показывающими ориентацию в мире."),
    ("chunk_section_paths", "Chunk Section Paths",
     "Draws the traversal paths the culling pass takes between chunk sections.",
     "Пути по секциям чанков",
     "Рисует пути обхода между секциями чанков, по которым идёт отсечение невидимого."),
    ("gpu_utilization", "GPU Utilization",
     "Graphics card load as a percentage, turning red under heavy load.",
     "Загрузка видеокарты",
     "Загрузка видеокарты в процентах, краснеет при высокой нагрузке."),
    ("simple_performance_impactors", "Performance Impactors",
     "Lists enabled settings that cost performance, such as clouds and improved transparency.",
     "Влияет на производительность",
     "Перечисляет включённые настройки, снижающие производительность: облака, улучшенную прозрачность и другие."),
    ("chunk_section_octree", "Chunk Section Octree",
     "Draws the octree the renderer uses to group chunk sections.",
     "Октодерево секций чанков",
     "Рисует октодерево, которым отрисовщик группирует секции чанков."),
    ("visualize_water_levels", "Water Levels",
     "Draws the fluid level of each water block.",
     "Уровни воды",
     "Рисует уровень жидкости у каждого блока воды."),
    ("visualize_heightmap", "Heightmap Surface",
     "Draws the heightmap surface above the terrain.",
     "Поверхность карты высот",
     "Рисует поверхность карты высот над рельефом."),
    ("visualize_collision_boxes", "Collision Boxes",
     "Draws the collision boxes entities actually collide with.",
     "Боксы столкновений",
     "Рисует боксы столкновений, с которыми реально сталкиваются существа."),
    ("visualize_entity_supporting_blocks", "Supporting Blocks",
     "Highlights the block each entity is standing on.",
     "Опорные блоки",
     "Подсвечивает блок, на котором стоит каждое существо."),
    ("visualize_block_light_levels", "Block Light Levels",
     "Draws the block light value at each position.",
     "Освещение от блоков",
     "Рисует значение освещения от блоков в каждой позиции."),
    ("visualize_sky_light_levels", "Sky Light Levels",
     "Draws the sky light value at each position.",
     "Освещение от неба",
     "Рисует значение небесного освещения в каждой позиции."),
    ("visualize_solid_faces", "Solid Faces",
     "Marks the block faces the game treats as solid.",
     "Сплошные грани",
     "Отмечает грани блоков, которые игра считает сплошными."),
    ("visualize_chunks_on_server", "Server Chunks",
     "Draws the status of each chunk on the server side.",
     "Чанки на сервере",
     "Рисует состояние каждого чанка на стороне сервера."),
    ("visualize_sky_light_sections", "Sky Light Sections",
     "Outlines the chunk sections the sky light engine tracks.",
     "Секции небесного света",
     "Обводит секции чанков, которые отслеживает движок небесного освещения."),
    ("chunk_section_visibility", "Chunk Section Visibility",
     "Draws which chunk sections the culling pass considers visible.",
     "Видимость секций чанков",
     "Рисует, какие секции чанков отсечение считает видимыми."),
]


def main() -> None:
    for idx, filename in ((0, "en_us.json"), (1, "ru_ru.json")):
        out = {key: value[idx] for key, value in UI.items()}

        for key, en_name, en_desc, ru_name, ru_desc in E:
            out[f"debugmenu.entry.{key}"] = en_name if idx == 0 else ru_name
            out[f"debugmenu.entry.{key}.desc"] = en_desc if idx == 0 else ru_desc

        path = ROOT / filename
        path.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
        print(filename, len(out), "keys")


if __name__ == "__main__":
    main()
